import "../../assets/style/main.scss"
import type { Metadata } from 'next'
import Header from '../../components/common/Header'
import Footer from '../../components/common/Footer'
import "bootstrap/dist/css/bootstrap.min.css"
import Grained from "../../components/common/Grained"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Grained />
        <Header />
        {children}
        <Footer />
        <script src="https://cdn.rawgit.com/sarathsaleem/grained/master/grained.js"></script>
      </body>
    </html>
  )
}
